"""Generate the nnU-Net trainer variants it does not ship — a loss or augmentation arm at OUR budget.

nnU-Net ships epoch variants of the PLAIN trainer (`nnUNetTrainer_250epochs`) and separately ships
loss and augmentation variants (`nnUNetTrainerDiceTopK10Loss`, `nnUNetTrainerDA5`). It does not ship
the cross product, so every loss or augmentation arm inherits the base 1000-epoch default. Exploring
at 1000 epochs costs about 7 GPU-h per arm to answer a question a quarter of that would answer.

frozen-wmh solved the same problem by generating the trainer, and this does it here: write a subclass
that sets `num_epochs` and nothing else, into the package nnU-Net searches.

**It writes into the INSTALLED nnunetv2 package**, which under `uv run --with` lives in a cache
directory that can be rebuilt. That is why this runs at job start rather than once: the generated file
is disposable and must be recreated whenever the environment is. It sets `num_epochs` and touches
nothing else, so an arm differs from its parent in budget alone.

  uv run --with nnunetv2 python scripts/make_nnunet_trainers.py nnUNetTrainerDiceTopK10Loss:250

Prints each generated class name, which is what `nnUNetv2_train -tr` then takes.
"""

import argparse
import importlib
import inspect
import os
import re
from pathlib import Path

# nnunetv2 is deliberately NOT a frozen-isles dependency -- this runs under `uv run --with nnunetv2`,
# the same arrangement as matplotlib. Importing it at module scope makes `just check` fail on an
# unresolvable import, so every nnU-Net import is function-local with the ignore the repo already uses.

TEMPLATE = '''"""GENERATED by scripts/make_nnunet_trainers.py — do not edit, and do not expect it to persist.

nnU-Net ships epoch variants of the plain trainer and, separately, loss and augmentation variants; it
does not ship the cross product. This is {parent} at {epochs} epochs and is otherwise identical to it.
"""

import torch

from nnunetv2.training.nnUNetTrainer.variants.{module} import {parent}


class {name}({parent}):
    # THE SIGNATURE MUST BE EXPLICIT. nnU-Net's base trainer introspects it:
    #     for k in inspect.signature(self.__init__).parameters.keys():
    #         self.my_init_kwargs[k] = locals()[k]
    # so `*args, **kwargs` makes it look for locals named "args" and "kwargs" and die on
    # KeyError: 'args' (job 201860, 47 s in, after taking a GPU). Restating upstream's signature is
    # the lesser evil: it breaks loudly if upstream changes, where the terse version breaks always.
    def __init__(self, plans: dict, configuration: str, fold: int, dataset_json: dict,
                 device: torch.device = torch.device("cuda")):
        super().__init__(plans, configuration, fold, dataset_json, device)
        self.num_epochs = {epochs}
'''
# A class definition, not the name in prose. Matching the bare string would let a docstring or a
# comment that quotes it win, and `module_of` takes the first hit it finds.
DEFINITION = "^class {parent}\\("


def variants_root() -> Path:
    from nnunetv2.training.nnUNetTrainer import variants  # pyright: ignore[reportMissingImports]

    return Path(variants.__file__).parent


def module_of(parent: str) -> str:
    """The dotted path under `variants` that defines `parent` — found by reading, never guessed."""
    root = variants_root()
    pattern = re.compile(DEFINITION.format(parent=re.escape(parent)), re.MULTILINE)
    found = [path for path in sorted(root.rglob("*.py")) if pattern.search(path.read_text())]
    if not found:
        raise SystemExit(f"FATAL: no variant module defines class {parent}")
    if len(found) > 1:
        raise SystemExit(f"FATAL: {len(found)} modules define class {parent} — {found}. Picking one "
                         f"silently would make the generated trainer's parent ambiguous.")
    return ".".join(found[0].relative_to(root).with_suffix("").parts)


def main() -> None:
    parser = argparse.ArgumentParser(description=__doc__,
                                     formatter_class=argparse.RawDescriptionHelpFormatter)
    parser.add_argument("specs", nargs="+", metavar="TRAINER:EPOCHS",
                        help="e.g. nnUNetTrainerDiceTopK10Loss:250")
    args = parser.parse_args()

    out_dir = variants_root() / "generated"
    out_dir.mkdir(exist_ok=True)
    (out_dir / "__init__.py").touch()

    import nnunetv2  # pyright: ignore[reportMissingImports]
    from nnunetv2.utilities.find_class_by_name import (  # pyright: ignore[reportMissingImports]
        recursive_find_python_class,
    )

    for spec in args.specs:
        if ":" not in spec:
            raise SystemExit(f"FATAL: expected TRAINER:EPOCHS, got {spec!r}")
        parent, epochs_text = spec.rsplit(":", 1)
        if not epochs_text.isdigit() or int(epochs_text) < 1:
            raise SystemExit(f"FATAL: epochs must be a positive integer, got {epochs_text!r}")
        epochs = int(epochs_text)
        name = f"{parent}_{epochs}epochs"
        module = module_of(parent)

        # Written atomically. Jobs run this concurrently, and a plain write lets one job import a
        # half-written file and die on a SyntaxError deep inside nnUNetv2_train, after it has taken
        # a GPU. os.replace is atomic within a filesystem.
        target = out_dir / f"{name}.py"
        scratch = target.with_suffix(f".py.{os.getpid()}.tmp")
        scratch.write_text(TEMPLATE.format(name=name, parent=parent, epochs=epochs, module=module))
        os.replace(scratch, target)

        # Import it back, and resolve it the way nnU-Net itself will, so a broken template fails HERE
        # rather than deep inside nnUNetv2_train after the job has queued and taken a GPU.
        importlib.invalidate_caches()
        importlib.import_module(f"nnunetv2.training.nnUNetTrainer.variants.generated.{name}")
        resolved = recursive_find_python_class(
            os.path.join(nnunetv2.__path__[0], "training", "nnUNetTrainer"),
            name,
            "nnunetv2.training.nnUNetTrainer",
        )
        if resolved is None:
            raise SystemExit(f"FATAL: nnU-Net cannot find {name} — it will not accept -tr {name}")
        if resolved.__mro__[1].__name__ != parent:
            raise SystemExit(f"FATAL: {name} resolved to a class whose parent is "
                             f"{resolved.__mro__[1].__name__}, not {parent}")
        # The point of the whole exercise: prove the budget actually took. A subclass that fails to
        # set num_epochs runs 1000 and silently costs 4x what was asked for.
        if resolved.__init__ is resolved.__mro__[1].__init__:
            raise SystemExit(f"FATAL: {name} did not override __init__, so num_epochs is still the "
                             f"parent's default")
        # nnU-Net reads this signature by name against its own locals(), so a variadic parameter is
        # fatal at construction. Checked here because the alternative is finding out on a GPU.
        variadic = [p.name for p in inspect.signature(resolved.__init__).parameters.values()
                    if p.kind in (p.VAR_POSITIONAL, p.VAR_KEYWORD)]
        if variadic:
            raise SystemExit(f"FATAL: {name}.__init__ takes variadic parameters {variadic}. nnU-Net "
                             f"introspects this signature and looks each name up in its own locals(), "
                             f"so it dies on KeyError. The signature must be explicit.")
        print(f"[generated] {name}  (from {parent}, {epochs} epochs)", flush=True)


if __name__ == "__main__":
    main()
